<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/whizline/image/upload/v1554365316/1x1.jpg" alt="Rogers Peter">
                        <h6>Rogers Peter Ukeje</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/iclone3" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/whizline" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://whizline.wordpress.com" target="_blank"<i class="fab fa-wordpress fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I'm an Android App Developer,I am also a wordpress developer and user based in Port Harcourt. love learning and would want to expand and sharpen my learning experience</p>
                        <br />
                        <h6>Skills</h6>
                        <p>PHP | Android | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
